"""
GitSentinel Configuration Manager
Handles loading, merging, and validating YAML configuration files.
"""

import os
from typing import Any, Dict, Optional

# Default configuration as Python dict (used as fallback)
DEFAULT_CONFIG: Dict[str, Any] = {
    "gitsentinel": {
        "version": "1.0.0",
        "enabled": True,
    },
    "scanning": {
        "parallel": True,
        "max_workers": 4,
        "max_file_size_mb": 10,
        "skip_binary": True,
    },
    "entropy": {
        "enabled": True,
        "threshold": 4.5,
        "hex_threshold": 3.0,
        "min_length": 12,
        "max_length": 256,
    },
    "severity": {
        "block_level": "HIGH",
    },
    "cache": {
        "enabled": True,
        "path": ".gitsentinel_cache.db",
    },
    "rules": {
        "aws": True,
        "jwt": True,
        "github": True,
        "generic": True,
    },
    "allowlist": {
        "values": [],
        "patterns": [],
        "files": [],
    },
    "reporting": {
        "format": "json",
        "output_dir": "reports",
    },
}


def _deep_merge(base: Dict[str, Any], override: Dict[str, Any]) -> Dict[str, Any]:
    """
    Deep merge two dictionaries. Override values take precedence.

    Args:
        base: Base configuration dictionary.
        override: Override configuration dictionary.

    Returns:
        Merged dictionary.
    """
    result = base.copy()
    for key, value in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def _find_config_file(start_dir: Optional[str] = None) -> Optional[str]:
    """
    Search for a GitSentinel config file starting from start_dir and walking up.

    Looks for: .gitsentinel.yml, .gitsentinel.yaml, gitsentinel.yml, gitsentinel.yaml

    Args:
        start_dir: Directory to start searching from. Defaults to CWD.

    Returns:
        Path to the config file, or None if not found.
    """
    if start_dir is None:
        start_dir = os.getcwd()

    config_names = [
        ".gitsentinel.yml",
        ".gitsentinel.yaml",
        "gitsentinel.yml",
        "gitsentinel.yaml",
    ]

    current = os.path.abspath(start_dir)
    # Walk up at most 10 levels to find config
    for _ in range(10):
        for name in config_names:
            candidate = os.path.join(current, name)
            if os.path.isfile(candidate):
                return candidate

        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent

    return None


def load_config(config_path: Optional[str] = None) -> Dict[str, Any]:
    """
    Load and merge GitSentinel configuration.

    Priority (highest to lowest):
    1. Explicitly provided config file
    2. Auto-discovered config file in repository
    3. Default built-in configuration

    Args:
        config_path: Optional explicit path to a config file.

    Returns:
        Merged configuration dictionary.
    """
    config = DEFAULT_CONFIG.copy()

    # Find config file
    if config_path is None:
        config_path = _find_config_file()

    if config_path and os.path.isfile(config_path):
        try:
            import yaml

            with open(config_path, "r", encoding="utf-8") as fh:
                user_config = yaml.safe_load(fh)

            if isinstance(user_config, dict):
                config = _deep_merge(config, user_config)
        except ImportError:
            # YAML not available, use defaults
            pass
        except Exception:
            # Invalid YAML, use defaults
            pass

    return config


def save_default_config(output_path: str) -> str:
    """
    Save the default configuration to a YAML file.

    Args:
        output_path: Path where the config file should be written.

    Returns:
        Absolute path to the written config file.
    """
    try:
        import yaml
    except ImportError:
        # Fallback: write as formatted text
        _write_config_fallback(output_path)
        return os.path.abspath(output_path)

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as fh:
        yaml.dump(
            DEFAULT_CONFIG,
            fh,
            default_flow_style=False,
            sort_keys=False,
            indent=2,
        )

    return os.path.abspath(output_path)


def _write_config_fallback(output_path: str) -> None:
    """Write config in YAML format manually (fallback when PyYAML unavailable)."""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    lines = [
        "# GitSentinel Configuration",
        "# Generated by GitSentinel",
        "",
        "gitsentinel:",
        "  version: '1.0.0'",
        "  enabled: true",
        "",
        "scanning:",
        "  parallel: true",
        "  max_workers: 4",
        "  max_file_size_mb: 10",
        "  skip_binary: true",
        "",
        "entropy:",
        "  enabled: true",
        "  threshold: 4.5",
        "  hex_threshold: 3.0",
        "  min_length: 12",
        "  max_length: 256",
        "",
        "severity:",
        "  block_level: HIGH",
        "",
        "cache:",
        "  enabled: true",
        "  path: .gitsentinel_cache.db",
        "",
        "rules:",
        "  aws: true",
        "  jwt: true",
        "  github: true",
        "  generic: true",
        "",
        "allowlist:",
        "  values: []",
        "  patterns: []",
        "  files: []",
        "",
        "reporting:",
        "  format: json",
        "  output_dir: reports",
        "",
    ]

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
